-- ============================================================================
-- Data export from the old Supabase project (pcvmdyhzufupgckszrdy).
-- Run AFTER 01_schema.sql on the new Lovable Cloud backend.
--
-- IMPORTANT:
--  * blocked_dates was empty - nothing to import.
--  * zoho_tokens is intentionally NOT exported (short-lived OAuth tokens,
--    re-authorise Zoho against the new backend instead).
--  * user_roles is at the BOTTOM and commented out: the rows reference
--    auth.users ids from the old project. Sign up again on the new backend,
--    then run the bootstrap-admin function or the statement at the bottom
--    with the NEW user ids.
--  * bookings.user_id has no FK to auth.users, so historic bookings import
--    cleanly even though their original owners no longer exist.
--  * The BEFORE INSERT trigger on bookings overwrites user_id with auth.uid().
--    It is disabled around the booking import below so the original owner ids
--    are preserved.
-- ============================================================================

BEGIN;

-- calendar_sync --------------------------------------------------------------
INSERT INTO public.calendar_sync (id,last_sync,sync_status,error_message,events_synced) VALUES ('6146958c-94ad-416f-9115-bc7d33e747b5','2025-06-02 20:21:34.58114+00','pending',NULL,0);

-- bookings -------------------------------------------------------------------
ALTER TABLE public.bookings DISABLE TRIGGER enforce_booking_user_id_trigger;
ALTER TABLE public.bookings DISABLE TRIGGER booking_status_change_trigger;

INSERT INTO public.bookings (id,created_at,user_id,menu_package,number_of_guests,season,starters,sides,desserts,extras,extra_salad_type,total_price,status,event_date,contact_name,contact_email,contact_phone,notes,venue_postal_code,additional_notes,address_line1,address_line2,city,province,postal_code_address,venue_name,venue_street_address,venue_city,venue_province,event_type,referral_source,menu_selection,booking_reference) VALUES ('920db1ff-08cc-44c0-8381-17c8274f9d1e','2025-06-17 15:26:08.23632+00','595f59c9-42a7-4dab-ae1a-dd347fb475e0','Essential Celebration',50,NULL,NULL,'Baby Carrots, Baby Onions',NULL,NULL,NULL,169,'pending','2025-06-22 00:00:00+00','Wade','wadethys@gmail.com','0823879626','','7608',NULL,'75 skool street',NULL,'Stellenbosch ','Western Cape ','7608',NULL,'75 Skool Street ','Stellenbosch','Western Cape','birthday','Facebook','{"sides": "Baby Carrots, Baby Onions", "extras": "", "season": null, "areaName": "Stellenbosch", "desserts": "", "starters": "", "eventType": "birthday", "travelFee": 0, "postalCode": "7608", "totalPrice": 169, "menuPackage": "Essential Celebration", "extraSaladType": "", "includeCutlery": true, "numberOfGuests": 50, "discountApplied": false}','TG971001CXZ');
INSERT INTO public.bookings (id,created_at,user_id,menu_package,number_of_guests,season,starters,sides,desserts,extras,extra_salad_type,total_price,status,event_date,contact_name,contact_email,contact_phone,notes,venue_postal_code,additional_notes,address_line1,address_line2,city,province,postal_code_address,venue_name,venue_street_address,venue_city,venue_province,event_type,referral_source,menu_selection,booking_reference) VALUES ('5f5ff8dd-d377-44ee-95b9-ebdf9cb0a27b','2025-06-23 09:02:54.587945+00','150e64d4-1a42-4984-b83e-d1f446856445','Deluxe Celebration Experience',50,NULL,NULL,'Baby Potatoes, Curry Noodle Salad',NULL,'Fruit Table',NULL,203,'pending','2025-07-20 00:00:00+00','Maroinielle Frazenburg','mfrazenburg01@gmail.com','0731913803','','7925',NULL,'Springfield Terrace Block C10, Off Roger Street',NULL,'ZONNEBLOEM','Western Cape ','7925',NULL,'Springfield Terrace Block C10, Off Roger Street','Observatory','Western Cape','birthday','Word of Mouth','{"sides": "Baby Potatoes, Curry Noodle Salad", "extras": "Fruit Table", "season": null, "areaName": "Observatory", "desserts": "", "starters": "", "eventType": "birthday", "travelFee": 750, "postalCode": "7925", "totalPrice": 203, "menuPackage": "Deluxe Celebration Experience", "extraSaladType": "", "includeCutlery": true, "numberOfGuests": 50, "discountApplied": false}','TG375755W8Q');
INSERT INTO public.bookings (id,created_at,user_id,menu_package,number_of_guests,season,starters,sides,desserts,extras,extra_salad_type,total_price,status,event_date,contact_name,contact_email,contact_phone,notes,venue_postal_code,additional_notes,address_line1,address_line2,city,province,postal_code_address,venue_name,venue_street_address,venue_city,venue_province,event_type,referral_source,menu_selection,booking_reference) VALUES ('fd541c0c-5bf0-481b-a683-be1ada2c945e','2025-06-23 09:16:57.792672+00','09c116a3-227a-42f2-a4dd-d179b7c32157','Essential Celebration',50,NULL,NULL,'Baby Potatoes, Baby Carrots',NULL,NULL,NULL,149,'pending','2025-12-27 00:00:00+00','Maria ','Maria.frazenburg@gmail.com','0839660705','','7925',NULL,'Block C10 Springfield Tarrace Woodstock ',NULL,'Cape Town ','Western Cape ','7925','Woodstock Hall ','Victoria road 98','Observatory','Western Cape','birthday','Facebook','{"sides": "Baby Potatoes, Baby Carrots", "extras": "", "season": null, "areaName": "Observatory", "desserts": "", "starters": "", "eventType": "birthday", "travelFee": 750, "postalCode": "7925", "totalPrice": 149, "menuPackage": "Essential Celebration", "extraSaladType": "", "includeCutlery": false, "numberOfGuests": 50, "discountApplied": false}','TG217538LLP');
INSERT INTO public.bookings (id,created_at,user_id,menu_package,number_of_guests,season,starters,sides,desserts,extras,extra_salad_type,total_price,status,event_date,contact_name,contact_email,contact_phone,notes,venue_postal_code,additional_notes,address_line1,address_line2,city,province,postal_code_address,venue_name,venue_street_address,venue_city,venue_province,event_type,referral_source,menu_selection,booking_reference) VALUES ('d8a99045-b0c2-4d2d-ad05-da08fce4fb08','2025-06-23 09:41:00.151931+00','eadfe282-aedb-49c3-a9c7-dbb4af297c8c','Signature Year-End Celebration',50,NULL,NULL,'Baby Carrots',NULL,NULL,NULL,160,'pending','2025-10-29 00:00:00+00','Donovan Frazenburg ','dfrazenburg@gmail.com','0833085036','','7798',NULL,'6 east close ',NULL,'Mitchell’s plain','Western Cape ','7798',NULL,'6 east close ','Strandfontein','Western Cape','yearend','Facebook','{"sides": "Baby Carrots", "extras": "", "season": null, "areaName": "Strandfontein", "desserts": "", "starters": "", "eventType": "yearend", "travelFee": 750, "postalCode": "7798", "totalPrice": 160, "menuPackage": "Signature Year-End Celebration", "extraSaladType": "", "includeCutlery": true, "numberOfGuests": 50, "discountApplied": false}','TG659228AK3');
INSERT INTO public.bookings (id,created_at,user_id,menu_package,number_of_guests,season,starters,sides,desserts,extras,extra_salad_type,total_price,status,event_date,contact_name,contact_email,contact_phone,notes,venue_postal_code,additional_notes,address_line1,address_line2,city,province,postal_code_address,venue_name,venue_street_address,venue_city,venue_province,event_type,referral_source,menu_selection,booking_reference) VALUES ('87dd3f6b-b5ac-41b1-aaca-bbb204a4fb97','2025-10-28 08:45:38.54498+00','02b9dde0-6ba4-434c-acaf-362fa6298db4','Signature Year-End Celebration',50,NULL,NULL,'Three Bean Salad, Baby Potatoes',NULL,NULL,NULL,160,'pending','2025-11-28 00:00:00+00','David du Plessis','dawie@sirctn.co.za','0832930449','Event at Clara anna Fontein','7550','Event at Clara anna Fontein','40 Haarlem street','Stellenberg Centre','Bellville','WC','7550','Madeleyn Inc','40 Haarlem street, Stellenberg Centre','Durbanville','Western Cape','yearend','Previous Customer','{"sides": "Three Bean Salad, Baby Potatoes", "extras": "", "season": null, "areaName": "Durbanville", "desserts": "", "starters": "", "eventType": "yearend", "travelFee": 500, "postalCode": "7550", "totalPrice": 160, "menuPackage": "Signature Year-End Celebration", "extraSaladType": "", "includeCutlery": true, "numberOfGuests": 50, "discountApplied": false}','TG139093PTS');
INSERT INTO public.bookings (id,created_at,user_id,menu_package,number_of_guests,season,starters,sides,desserts,extras,extra_salad_type,total_price,status,event_date,contact_name,contact_email,contact_phone,notes,venue_postal_code,additional_notes,address_line1,address_line2,city,province,postal_code_address,venue_name,venue_street_address,venue_city,venue_province,event_type,referral_source,menu_selection,booking_reference) VALUES ('39246736-87bd-438e-b45f-3b17ba15e39d','2025-08-19 21:38:36.893068+00','a894d4f9-c1ea-472b-b394-78f1fbbd65bd','Essential Celebration',50,NULL,NULL,'Baby Carrots, Baby Onions',NULL,NULL,NULL,169,'cancelled','2025-12-20 00:00:00+00','Denzel Thys','denzel@thysgemaak.com','0674567784','','8001',NULL,'75 School Street',NULL,'Kylemore, Western Cape, South Africa','Western Cape','7608','Thys Gemaak SDC','75 Long Street','Cape Town (CBD)','Western Cape','birthday','Facebook','{"sides": "Baby Carrots, Baby Onions", "extras": "", "season": null, "areaName": "Cape Town (CBD)", "desserts": "", "starters": "", "eventType": "birthday", "travelFee": 750, "postalCode": "8001", "totalPrice": 169, "menuPackage": "Essential Celebration", "extraSaladType": "", "includeCutlery": true, "numberOfGuests": 50, "discountApplied": false}','TG516653X8A');
INSERT INTO public.bookings (id,created_at,user_id,menu_package,number_of_guests,season,starters,sides,desserts,extras,extra_salad_type,total_price,status,event_date,contact_name,contact_email,contact_phone,notes,venue_postal_code,additional_notes,address_line1,address_line2,city,province,postal_code_address,venue_name,venue_street_address,venue_city,venue_province,event_type,referral_source,menu_selection,booking_reference) VALUES ('af9c81af-423b-4309-847e-eea2a366d4b6','2025-08-20 12:48:02.025348+00','7f6fae69-68bc-467d-befc-44609af01ea5','Essential Celebration',50,NULL,NULL,'Baby Carrots, Baby Onions',NULL,'Cheese Table',NULL,207,'cancelled','2025-12-20 00:00:00+00','Denzel Thys','denzel@thysgemaak.com','0674567784','','8001',NULL,'75 School Street',NULL,'Kylemore, Western Cape, South Africa','Western Cape','7608','Thys Gemaak SDC','75 Long Street','Cape Town (CBD)','Western Cape','birthday','TikTok','{"sides": "Baby Carrots, Baby Onions", "extras": "Cheese Table", "season": null, "areaName": "Cape Town (CBD)", "desserts": "", "starters": "", "eventType": "birthday", "travelFee": 750, "postalCode": "8001", "totalPrice": 207, "menuPackage": "Essential Celebration", "extraSaladType": "", "includeCutlery": true, "numberOfGuests": 50, "discountApplied": false}','TG081928WFV');

ALTER TABLE public.bookings ENABLE TRIGGER enforce_booking_user_id_trigger;
ALTER TABLE public.bookings ENABLE TRIGGER booking_status_change_trigger;

COMMIT;

-- event_availability: see 03_event_availability.sql (90 rows)

-- ----------------------------------------------------------------------------
-- user_roles: re-point at the NEW auth user ids after signing up again.
-- Old rows were:
--   denzel@thysgemaak.com -> admin
--   wade@thysgemaak.com   -> admin
-- Run once the accounts exist on the new backend:
--
-- INSERT INTO public.user_roles (user_id, role)
-- SELECT id, 'admin'::public.app_role FROM auth.users
-- WHERE email IN ('denzel@thysgemaak.com', 'wade@thysgemaak.com')
-- ON CONFLICT (user_id, role) DO NOTHING;
-- ----------------------------------------------------------------------------
