// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcvmdyhzufupgckszrdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjdm1keWh6dWZ1cGdja3N6cmR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMTI0ODEsImV4cCI6MjA1ODY4ODQ4MX0.hNNiDqgi8MDavGcP7Bwc2KR59CTsdWAw8g4gdSr_Kq0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);